language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ree
  - rbx
before_install:
  - wget https://dl.dropbox.com/u/2175127/libre2-dev_20130802_amd64.deb
  - sudo dpkg -i libre2-dev_20130802_amd64.deb
  - gem install bundler -v '~> 1.11'
